import type { Metadata } from "next";
import Link from 'next/link'
// import { Toaster } from "@/components/ui/toaster"
import DashboardLayout from "./dashboard/dashboard";

export const metadata: Metadata = {
  title: "CodeBootcamp.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <DashboardLayout>
        <div className="overflow-y-scroll">
            { children }
        </div>
    </DashboardLayout>
  );
}