import type { Metadata } from "next"
import Header from './(layout)/header'

// imports ...

export const metadata: Metadata = {
  title: "CodeBootcamp.com",
  description: "Generated by create next app",
};


export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className={'bg-white h-full'}>
        <Header />
        <div className="p-8 pt-1 h-full mt-[100px]">
            { children }
        </div>
    </div>
  );
}