import type { Metadata } from "next"
import Header from './(layout)/header'
import Footer from "./(layout)/footer"

// imports ...

export const metadata: Metadata = {
  title: "CodeBootcamp.com",
  description: "Generated by create next app",
};


export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <div>
        <Header />
        <div className="p-8 pt-1">
            { children }
        </div>
        <Footer />
    </div>
  );
}