import type { Metadata } from "next"
import AdminAuthCheck from "./auth.flow/component"
import Header from "./(layout)/header"

export const metadata: Metadata = {
  title: "CodeBootcamp.com",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
      <AdminAuthCheck>
         <Header />
        { children }
      </AdminAuthCheck>
  );
}