import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from 'next/link'
import { ClerkProvider } from '@clerk/nextjs'
// import { Toaster } from "@/components/ui/toaster"
import DashboardLayout from "./dashboard/dashboard";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        <html className="h-full" lang="en">
        <body className='h-full overflow-hidden'>
            <DashboardLayout>
                { children }
                {/* <Toaster />  */}
            </DashboardLayout>
        </body>
      </html>
    </ClerkProvider>
  );
}

