import type { Metadata } from "next"
import { SignInButton, SignedIn, SignedOut } from "@clerk/nextjs"
import AdminAuthCheck from "../authFlows/auth.admin/component"
import NotAllowedAccessView from "../authFlows/notAllowedView"

export const metadata: Metadata = {
  title: "CodeBootcamp.com",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <SignedIn>
        <AdminAuthCheck>
            { children }
         </AdminAuthCheck>
      </SignedIn>
      <SignedOut>
          <NotAllowedAccessView>
              <div>
                  you're not currently signed in.
              </div>
          </NotAllowedAccessView>
      </SignedOut>
    </>
  );
}