import type { Metadata } from "next"
import Title from "../../reusables/content/title"
import Link from "next/link"

export const metadata: Metadata = {
  title: "CodeBootcamp.com",
  description: "Generated by create next app",
};


export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
        <div className="p-5">
            <Title title="Content Work" variant="heading" />
            <div className=" mt-5 flex min-h-screen w-full flex-col bg-gray-100 p-5 rounded-lg">
               { children }
            </div>
        </div>
  );
}