import type { Metadata } from "next"
import DashboardLayout from "./(layout)"
import AnalyticsPopover from "./tracking/component";
import TimerMusicPlayer from "./zenMode/component";

export const metadata: Metadata = {
  title: "CodeBootcamp.com",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
      <>
          <AnalyticsPopover />
          <TimerMusicPlayer />
          <DashboardLayout>
              { children }
          </DashboardLayout>
      </>
  );
}